<?php

namespace dhl;

use dhl\Type;
use Phpro\SoapClient\Soap\ClassMap\ClassMapCollection;
use Phpro\SoapClient\Soap\ClassMap\ClassMap;

class exampleClassmap
{

    public static function getCollection() : \Phpro\SoapClient\Soap\ClassMap\ClassMapCollection
    {
        return new ClassMapCollection([
            new ClassMap('Version', Type\Version::class),
            new ClassMap('AuthentificationType', Type\AuthentificationType::class),
            new ClassMap('NativeAddressType', Type\NativeAddressType::class),
            new ClassMap('ReceiverNativeAddressType', Type\ReceiverNativeAddressType::class),
            new ClassMap('PickupAddressType', Type\PickupAddressType::class),
            new ClassMap('DeliveryAddressType', Type\DeliveryAddressType::class),
            new ClassMap('BankType', Type\BankType::class),
            new ClassMap('NameType', Type\NameType::class),
            new ClassMap('ReceiverNameType', Type\ReceiverNameType::class),
            new ClassMap('CommunicationType', Type\CommunicationType::class),
            new ClassMap('ContactType', Type\ContactType::class),
            new ClassMap('PackStationType', Type\PackStationType::class),
            new ClassMap('PostfilialeType', Type\PostfilialeType::class),
            new ClassMap('ParcelShopType', Type\ParcelShopType::class),
            new ClassMap('CustomerType', Type\CustomerType::class),
            new ClassMap('ErrorType', Type\ErrorType::class),
            new ClassMap('CountryType', Type\CountryType::class),
            new ClassMap('ShipmentNumberType', Type\ShipmentNumberType::class),
            new ClassMap('Status', Type\Status::class),
            new ClassMap('Dimension', Type\Dimension::class),
            new ClassMap('TimeFrame', Type\TimeFrame::class),
            new ClassMap('GetVersionResponse', Type\GetVersionResponse::class),
            new ClassMap('CreateShipmentOrderRequest', Type\CreateShipmentOrderRequest::class),
            new ClassMap('ValidateShipmentOrderRequest', Type\ValidateShipmentOrderRequest::class),
            new ClassMap('CreateShipmentOrderResponse', Type\CreateShipmentOrderResponse::class),
            new ClassMap('ValidateShipmentResponse', Type\ValidateShipmentResponse::class),
            new ClassMap('GetLabelRequest', Type\GetLabelRequest::class),
            new ClassMap('GetLabelResponse', Type\GetLabelResponse::class),
            new ClassMap('DoManifestRequest', Type\DoManifestRequest::class),
            new ClassMap('DoManifestResponse', Type\DoManifestResponse::class),
            new ClassMap('DeleteShipmentOrderRequest', Type\DeleteShipmentOrderRequest::class),
            new ClassMap('DeleteShipmentOrderResponse', Type\DeleteShipmentOrderResponse::class),
            new ClassMap('GetExportDocRequest', Type\GetExportDocRequest::class),
            new ClassMap('GetExportDocResponse', Type\GetExportDocResponse::class),
            new ClassMap('GetManifestRequest', Type\GetManifestRequest::class),
            new ClassMap('GetManifestResponse', Type\GetManifestResponse::class),
            new ClassMap('UpdateShipmentOrderRequest', Type\UpdateShipmentOrderRequest::class),
            new ClassMap('UpdateShipmentOrderResponse', Type\UpdateShipmentOrderResponse::class),
            new ClassMap('CreationState', Type\CreationState::class),
            new ClassMap('ValidationState', Type\ValidationState::class),
            new ClassMap('Statusinformation', Type\Statusinformation::class),
            new ClassMap('PieceInformation', Type\PieceInformation::class),
            new ClassMap('ShipmentOrderType', Type\ShipmentOrderType::class),
            new ClassMap('Shipment', Type\Shipment::class),
            new ClassMap('ValidateShipmentOrderType', Type\ValidateShipmentOrderType::class),
            new ClassMap('ShipperTypeType', Type\ShipperTypeType::class),
            new ClassMap('ShipperType', Type\ShipperType::class),
            new ClassMap('ReceiverTypeType', Type\ReceiverTypeType::class),
            new ClassMap('ReceiverType', Type\ReceiverType::class),
            new ClassMap('Ident', Type\Ident::class),
            new ClassMap('ShipmentDetailsType', Type\ShipmentDetailsType::class),
            new ClassMap('ShipmentDetailsTypeType', Type\ShipmentDetailsTypeType::class),
            new ClassMap('ShipmentItemType', Type\ShipmentItemType::class),
            new ClassMap('ShipmentItemTypeType', Type\ShipmentItemTypeType::class),
            new ClassMap('ShipmentService', Type\ShipmentService::class),
            new ClassMap('Serviceconfiguration', Type\Serviceconfiguration::class),
            new ClassMap('ServiceconfigurationDetails', Type\ServiceconfigurationDetails::class),
            new ClassMap('ServiceconfigurationDetailsOptional', Type\ServiceconfigurationDetailsOptional::class),
            new ClassMap('ServiceconfigurationDetailsResponse', Type\ServiceconfigurationDetailsResponse::class),
            new ClassMap('ServiceconfigurationType', Type\ServiceconfigurationType::class),
            new ClassMap('ServiceconfigurationEndorsement', Type\ServiceconfigurationEndorsement::class),
            new ClassMap('ServiceconfigurationISR', Type\ServiceconfigurationISR::class),
            new ClassMap('ServiceconfigurationDH', Type\ServiceconfigurationDH::class),
            new ClassMap('ServiceconfigurationVisualAgeCheck', Type\ServiceconfigurationVisualAgeCheck::class),
            new ClassMap('ServiceconfigurationDeliveryTimeframe', Type\ServiceconfigurationDeliveryTimeframe::class),
            new ClassMap('ServiceconfigurationDateOfDelivery', Type\ServiceconfigurationDateOfDelivery::class),
            new ClassMap('ServiceconfigurationAdditionalInsurance', Type\ServiceconfigurationAdditionalInsurance::class),
            new ClassMap('ServiceconfigurationCashOnDelivery', Type\ServiceconfigurationCashOnDelivery::class),
            new ClassMap('ServiceconfigurationShipmentHandling', Type\ServiceconfigurationShipmentHandling::class),
            new ClassMap('ServiceconfigurationUnfree', Type\ServiceconfigurationUnfree::class),
            new ClassMap('ServiceconfigurationIC', Type\ServiceconfigurationIC::class),
            new ClassMap('ShipmentNotificationType', Type\ShipmentNotificationType::class),
            new ClassMap('ExportDocumentType', Type\ExportDocumentType::class),
            new ClassMap('ExportDocPosition', Type\ExportDocPosition::class),
            new ClassMap('FurtherAddressesType', Type\FurtherAddressesType::class),
            new ClassMap('DeliveryAdress', Type\DeliveryAdress::class),
            new ClassMap('LabelData', Type\LabelData::class),
            new ClassMap('ExportDocData', Type\ExportDocData::class),
            new ClassMap('ManifestState', Type\ManifestState::class),
            new ClassMap('DeletionState', Type\DeletionState::class),
            new ClassMap('BookPickupRequest', Type\BookPickupRequest::class),
            new ClassMap('BookPickupResponse', Type\BookPickupResponse::class),
            new ClassMap('PickupDetailsType', Type\PickupDetailsType::class),
            new ClassMap('PickupOrdererType', Type\PickupOrdererType::class),
            new ClassMap('PickupBookingInformationType', Type\PickupBookingInformationType::class),
            new ClassMap('CancelPickupRequest', Type\CancelPickupRequest::class),
            new ClassMap('CancelPickupResponse', Type\CancelPickupResponse::class),
            new ClassMap('IdentityData', Type\IdentityData::class),
            new ClassMap('DrivingLicense', Type\DrivingLicense::class),
            new ClassMap('IdentityCard', Type\IdentityCard::class),
            new ClassMap('BankCard', Type\BankCard::class),
            new ClassMap('PackstationType', Type\PackstationType::class),
            new ClassMap('ReadShipmentOrderResponse', Type\ReadShipmentOrderResponse::class),
        ]);
    }


}

